### ISSUE TITLE
Version 0.2.0 says its 0.1.3

### ISSUE THREAD

**Issue by adocampo** [asrul10/linux-command-gpt#11]
I had version 0.1.3 installed and I've just downloaded latest version, 0.2.0. But when I run `lcg --version` it says it's version 0.1.3
![image](https://github.com/asrul10/linux-command-gpt/assets/2266612/5de7b1fa-7a46-4941-bf88-f744be8e6c66)

**Comment by asrul10** [comment]
Yes, I am aware of it, you are using the latest version 0.2.0.

The only issue is the command `--version` will fix it soon
