### ISSUE TITLE
some commands not working

### ISSUE THREAD

**Issue by attam** [asrul10/linux-command-gpt#2]
great work here. I have noticed commands such as 'cd' and 'cat' not working. For example, with 'cd', I get:

> exec: "cd": executable file not found in $PATH

and with 'cat', I get:

> exit status 1

When I run the proposed commands in a separate terminal, they all work properly.
I'm just starting to use the tool, and most other commands are working well directly from your program. I think your tool has great potential as a self-learning tool for linux beginners or even more experienced users, since it acts as an interface between the users' thoughts and the appropriate terminal command.

**Comment by billyblackburn** [comment]
what OS are you on?  thats strange for a unix system

**Comment by attam** [comment]
```
$ uname -a
```
Linux archlinux 6.2.2-arch1-1

**Comment by billyblackburn** [comment]
ok, so cat requires an argument, that what exit status 1 is trying to tell you....
and cd is a "built in" on my shell and probably on yours too.." so its not going to be in the $PATH like the others
try this 
bly@pop-os:~$ type -a cd
cd is a shell builtin
bly@pop-os:~$ type -a tar
tar is /usr/bin/tar
tar is /bin/tar
it will find tar, but it wont find cd since its "built in" to the shell.

**Comment by asrul10** [comment]
It's valid; it will happen on the shell built-in. I will try to figure it out if I have some time

**Comment by Zeioth** [comment]
Same issue here. Exit code 2.
![screenshot_2023-03-18_22-37-10_063336191](https://user-images.githubusercontent.com/3357792/226141431-4c56b5e6-8803-4a3d-8720-340c83b430f5.png)

**Comment by billyblackburn** [comment]
Exit code 2 signifies invalid usage of some shell built-in command.
Examples of built-in commands include alias, echo, and printf.

I've never written in Go but its not too different from python so I'm going to guess that it's
the way that Go interfaces with the shell.
I think this might be helpful to the OP.  

https://blog.kowalczyk.info/article/wOYk/advanced-command-execution-in-go-with-osexec.html
the code is running but its not sending the output to the terminal...
here is example from the link

func main() {
    cmd := exec.Command("ls", "-lah")
    var stdout, stderr bytes.Buffer
    cmd.Stdout = &stdout
    cmd.Stderr = &stderr
    err := cmd.Run()
    if err != nil {
        log.Fatalf("cmd.Run() failed with %s\n", err)
    }
    outStr, errStr := string(stdout.Bytes()), string(stderr.Bytes())
    fmt.Printf("out:\n%s\nerr:\n%s\n", outStr, errStr)
}

if you dont get to it first I will try tomorrow.  I want to try out some Go 👍🏽

**Comment by asrul10** [comment]
Closed `execute` feature was replaced with copy to clipboard
