### ISSUE TITLE
AUR package needed

### ISSUE THREAD

**Issue by Zeioth** [asrul10/linux-command-gpt#3]
I'm planing to do it myself during this week, but if someone has time to do it first, that would be cool.

**Comment by asrul10** [comment]
Awesome that you're planning on doing it yourself, but if someone else wants to jump in and take care of it, that'd be cool too! Either way, I'm sure it'll turn out great!

**Comment by Zeioth** [comment]
The package is [available on AUR now](https://aur.archlinux.org/packages/linux-command-gpt-git) as linux-command-gpt-git. 
I'm gonna give it a couple days for people to test it before closing this ticket.

EDIT: Also added  a [linux-command-gpt stable repo](https://aur.archlinux.org/packages/linux-command-gpt), so we can experiment safely.

**Comment by asrul10** [comment]
Cool, thanks for your effort. I will try it soon.
