### ISSUE TITLE
Usage With FISH

### ISSUE THREAD

**Issue by smiddy-001** [asrul10/linux-command-gpt#4]
Hiya, new to fish shell and everything but fish ain't liking the lcg command.
`lcg --version`
returns
`fish: Unknown command: lcg`

**Comment by asrul10** [comment]
I just heard about the Fish shell from you. I think you need to add 'lcg' to the environment PATH like this:
```bash
fish_add_path ~/.linux-command-gpt/lcg
```
Source: https://fishshell.com/docs/current/cmds/fish_add_path.html
