### ISSUE TITLE
Feature proposal: (R)e-generate command

### ISSUE THREAD

**Issue by Zeioth** [asrul10/linux-command-gpt#5]
The current

    Are you sure you want to execute the command? (Y/n):

Should be 

    Are you sure you want to execute the command? (Y/n/r):

Where 'r' sends the question again to chatGPT to generate a new answer.

**Comment by billyblackburn** [comment]
Im not sure i agree with you, but maybe you could use a 'goto' statement here.  I might try to do this tomorrow if I get some free time.  I'm learning to code so it might be a good exercise

fmt.Print("Are you sure you want to execute the command? (Y/n/r): ")
	fmt.Scanln(&c)
        if c = "r" {
        goto line 119
        }
	if c != "Y" && c != "y" {
		return
	}

**Comment by asrul10** [comment]
your idea is cool. I think it should be implemented because sometimes I get an invalid command. I am also planning to add an argument, like this, 
```bash
lcg --explain
```
that will print an explanation table for each argument of the command. What do you think?

**Comment by billyblackburn** [comment]
i think its a good idea..
