### ISSUE TITLE
Feature request (usability improvement): When lcg is called withiut any argument, ask for it

### ISSUE THREAD

**Issue by Zeioth** [asrul10/linux-command-gpt#7]
Currently, when we run gptc, this is displayed

```
Usage: lcg [options]

  --help         output usage information
  --version      output the version number
  --update-key   update the API key
  --delete-key   delete the API key
```

It would be ideal to prompt the user to enter text.

**Comment by asrul10** [comment]
Understand, my approach to the solution will add some examples instead of a validation message. What do you think?

**Comment by Zeioth** [comment]
Yeah anything is fine. It's just for clarity.
