### ISSUE TITLE
Raspberry Pi 4 support?

### ISSUE THREAD

**Issue by iMord0** [asrul10/linux-command-gpt#9]
After completing steps from installation lcg doesn't work.
My go installation is for arm64 and it works and completes the build command.
But after creating a symlink when I try to run the command I get "command not found" or when in ~/.linux-command-gpt it says "cannot execute binary file".

**Comment by asrul10** [comment]
Where do you create symlink?
Can you show me your $PATH?

I assume the target symlink is not available in $PATH

**Comment by iMord0** [comment]
For symlink I have just used the command provided in installation guide:
> ln -s ~/.linux-command-gpt/lcg ~/.local/bin

There is my $PATH:
> echo $PATH
> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin

**Comment by asrul10** [comment]
You need add your ~/.local/bin to your $PATH through .bashrc or .zshrc.
Another solution make symlink to /usr/local/go/bin

**Comment by iMord0** [comment]
Something like that? Sorry I this is a dumb question, but my knowledge on linux is limited.
> ln -s ~/.linux-command-gpt/lcg /usr/local/go/bin

Or can you tell me how to add this to $PATH correctly?

**Comment by asrul10** [comment]
That is correct symlink, but you need `sudo` command as I know /user/ is owned by root

**Comment by iMord0** [comment]
Working, thanks a lot!
